[source]
type = "UtxoRPC"
url = "http://127.0.0.1:50051"

[intersect]
type = "Tip"

[reduce]
type = "Deno"
main_module = "/home/aleksandar/Projects/scrolls/examples/rdbms/run.js"
storage_event = "RDBMS"

[storage]
type = "Postgres"
url = "postgresql://postgres:password@localhost:5432/scrolls"