[source]
type = "UtxoRPC"
url = "http://127.0.0.1:50051"

[intersect]
type = "Tip"

[reduce]
type = "Deno"
deps = "/home/aleksandar/Projects/scrolls/scrolls/src/reduce/deno/deps.js"
reducers = [
    "/home/aleksandar/Projects/scrolls/scrolls/src/reduce/deno/balance_by_address.js",
    "/home/aleksandar/Projects/scrolls/scrolls/src/reduce/deno/balance_by_stake_key.js",
]

[storage]
type = "Redis"
url = "redis://localhost:6379"
stream_name = "my-stream"